#!/bin/bash

# Copy/paste this job script into a text file and submit with the command:
#    sbatch thefilename
# job standard output will go to the file slurm-%j.out (where %j is the job ID)

#SBATCH --time=1:00:00   # walltime limit (HH:MM:SS)
#SBATCH --nodes=16   # number of nodes
#SBATCH --ntasks-per-node=1    #  1 processor core(s) per node

# LOAD MODULES, INSERT CODE, AND RUN YOUR PROGRAMS HERE
module load intel
make clean
make
mpirun -np 16 ./main.exe 320 > output.data
