#!/bin/bash

# Copy/paste this job script into a text file and submit with the command:
#    sbatch thefilename
# job standard output will go to the file slurm-%j.out (where %j is the job ID)

#SBATCH --time=1:00:00   # walltime limit (HH:MM:SS)
#SBATCH --nodes=1   # number of nodes
#SBATCH --ntasks-per-node=16   # 16 processor core(s) per node

# LOAD MODULES, INSERT CODE, AND RUN YOUR PROGRAMS HERE

./main.exe 1  16777216 > output01.txt
./main.exe 2  16777216 > output02.txt
./main.exe 4  16777216 > output04.txt
./main.exe 8  16777216 > output08.txt
./main.exe 16 16777216 > output16.txt
